/**
 * Driver domain types.
 *
 * Every union below is a copy of a Prisma enum in the backend schema. If a value
 * is not here, the server cannot produce it, and the UI must not branch on it.
 * Notably there is no EXPIRED document status and no DRIVER_WAITING trip state,
 * even though the original product brief mentioned both.
 *
 * DriverProfile is transcribed field by field from DriverSelfService.serialize()
 * (modules/drivers/driver-self.service.ts). It is NOT symmetrical with the
 * update body: the server RETURNS a nested `vehicle` object but ACCEPTS flat
 * `carMake` / `carModel` / ... fields. Both shapes are modelled separately
 * instead of being merged, because merging them would mean guessing.
 */
export type DriverStatus =
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "SUSPENDED"
  | "BANNED";

export type DriverAvailability = "OFFLINE" | "ONLINE" | "ON_TRIP";

/** Mirrors DOC_TYPES in modules/drivers/dto/driver-self.dto.ts. */
export const DOCUMENT_TYPES = [
  "LICENSE",
  "ID_CARD",
  "INSURANCE",
  "REGISTRATION",
  "PROFILE_PHOTO",
] as const;
export type DocumentType = (typeof DOCUMENT_TYPES)[number];

/** No EXPIRED: the server enum has exactly these three members. */
export type DocumentStatus = "PENDING" | "APPROVED" | "REJECTED";

export type VehicleVerificationStatus = "PENDING" | "APPROVED" | "REJECTED";

/** Mirrors RIDE_CLASSES in modules/drivers/dto/driver-self.dto.ts. */
export const RIDE_CLASSES = [
  "ECONOMY",
  "COMFORT",
  "VAN",
  "XL",
  "CAR",
  "BIKE",
] as const;
export type RideClass = (typeof RIDE_CLASSES)[number];

/**
 * One row of driver.documents as serialized by the server.
 *
 * `url` is generated per request from the stored object key, so it is safe to
 * display but must never be written back or cached across sessions.
 */
export type DriverDocument = {
  id: string;
  type: DocumentType;
  url: string | null;
  status: DocumentStatus;
};

/** driver.vehicle: the single ACTIVE vehicle, or null when none exists yet. */
export type DriverVehicle = {
  id: string;
  make: string | null;
  model: string | null;
  color: string | null;
  plate: string | null;
  year: number | null;
  rideClass: RideClass | null;
  vehicleTypeId: string | null;
};

/** Exact shape of GET /driver/me. */
export type DriverProfile = {
  id: string;
  userId: string;
  name: string | null;
  phone: string | null;
  email: string | null;
  /**
   * Display URL generated by the server on every read from the stored object
   * key: user.avatarUrl first, then the PROFILE_PHOTO document.
   */
  photoUrl: string | null;
  status: DriverStatus;
  /** Server-computed convenience flag; equals status === "APPROVED". */
  approved: boolean;
  availability: DriverAvailability;
  rating: number;
  totalTrips: number;
  /**
   * Phase 11 - read-only, computed by the backend from COMPLETED trips only.
   * The app never sends these fields and never derives a level from a count:
   * no threshold (10 / 50 / 100 / 500) exists anywhere in this codebase.
   */
  completedTripsCount?: number | null;
  profileLevel?: string | null;
  /** Public frame URL built server-side from the R2 object key. */
  profileFrameUrl?: string | null;
  nextLevel?: string | null;
  nextLevelAt?: number | null;
  tripsToNextLevel?: number | null;
  cityId: string | null;
  /** City NAME, not the id. The id is `cityId`. */
  city: string | null;
  vehicle: DriverVehicle | null;
  documents: DriverDocument[];
};

/**
 * PATCH /driver/me body (UpdateDriverProfileDto).
 *
 * Every field is optional and only what the driver changed should be sent:
 * touching any vehicle identity field (make / model / plate / year) makes the
 * server reset the vehicle verification back to PENDING, so sending unchanged
 * values would silently invalidate an approved vehicle.
 *
 * rideClass / vehicleTypeId are deliberately absent: the driver no longer
 * sets their own service class. It is assigned by staff during vehicle
 * review (PATCH /vehicles/:id/verify on the backend), so a driver cannot
 * silently reclassify an approved vehicle to chase more ride offers.
 */
export type UpdateDriverProfileInput = {
  name?: string;
  phone?: string;
  carMake?: string;
  carModel?: string;
  carColor?: string;
  carPlate?: string;
  carYear?: number;
  cityId?: string;
};

/** Response of POST /driver/me/upload-url. */
export type UploadTicket = {
  /** Presigned PUT URL. Valid for 30 minutes. */
  uploadUrl: string;
  /**
   * Object key in storage, e.g. "driver-docs/<driverId>/LICENSE-<ts>.jpg".
   * THIS is what gets registered with POST /driver/me/documents.
   */
  objectPath: string;
  /**
   * Ready-to-display URL for this object: the permanent public URL when
   * R2_PUBLIC_URL is set, otherwise a temporary signed one. For immediate
   * preview only - never persist it and never send it back to the server.
   */
  readUrl: string;
};

/** The authenticated account behind the driver, from POST /auth/me. */
export type AuthUser = {
  id: string;
  phone?: string | null;
  name?: string | null;
  email?: string | null;
  role: string;
  avatarUrl?: string | null;
};

/** Latest document per type, newest first as returned by the server. */
export function latestDocument(
  documents: DriverDocument[] | undefined,
  type: DocumentType,
): DriverDocument | null {
  if (!documents) return null;
  return documents.find((document) => document.type === type) ?? null;
}
